"""initial migration

Revision ID: 5cdddd3f0eb4
Revises: 
Create Date: 2024-01-03 19:40:48.425498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdddd3f0eb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('article',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('contents', sa.String(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.name'], ),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('user')
    # ### end Alembic commands ###
